### ISSUE TITLE
Not compiling CoreASM out of box?

### ISSUE THREAD

**Issue by Bazmundi** [CoreASM/coreasm.core#19]
Added coreASM to my epsilon toy box.

Copy and pasted Dining Philosophers into new *.casm file over default text.

Got:

INFO - parsing file D:\Safety\epsilon\safetyw\coreasm_sandpit\untitled.casm
org.asmeta.parser.ParseException: Encountered " <ID_DOMAIN> "CoreASM "" at line 7, column 1.
Was expecting one of:
    "asm" ...
    "module" ...
    "asyncr" ...
    
	at org.asmeta.parser.ASMParser.generateParseException(ASMParser.java:9365)
	at org.asmeta.parser.ASMParser.jj_consume_token(ASMParser.java:9238)
	at org.asmeta.parser.ASMParser.Asm(ASMParser.java:188)
	at org.asmeta.parser.ASMParser.setUpReadAsm(ASMParser.java:114)
	at org.asmeta.eclipse.editor.actions.ParseJob.run(ParseJob.java:77)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Tried compiling boiler plate code that comes with new file, got:

INFO - parsing file D:\Safety\epsilon\safetyw\coreasm_sandpit\untitled2.casm
org.asmeta.parser.ParseException: Encountered " <ID_DOMAIN> "CoreASM "" at line 1, column 1.
Was expecting one of:
    "asm" ...
    "module" ...
    "asyncr" ...
    
	at org.asmeta.parser.ASMParser.generateParseException(ASMParser.java:9365)
	at org.asmeta.parser.ASMParser.jj_consume_token(ASMParser.java:9238)
	at org.asmeta.parser.ASMParser.Asm(ASMParser.java:188)
	at org.asmeta.parser.ASMParser.setUpReadAsm(ASMParser.java:114)
	at org.asmeta.eclipse.editor.actions.ParseJob.run(ParseJob.java:77)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Seems to not want to run from Run menu, but will run from buttons on menu bar?

Any configuration that I am missing?  There appears nothing to set up other than the install?

Cheers,
A

**Comment by mdausend** [comment]
Dear Bazmudi,

thank you for your question but I have to forward you to our friends in Italy. According to your stack trace, it seems that you are using ASMETA and not CoreASM.
../org/asmeta/parser/ASMParser.jj
It seems that they integrated our common UASM-parser and therefore the parse exception states: Encountered " "CoreASM "...

Please contact them in order to get some assistance. Probably, they can help you better than me this time.

http://asmeta.sourceforge.net

Kind regards
Marcel

**Comment by Bazmundi** [comment]
Whoops.  I did get my wires crossed there.  Thanks for that.

Cheers,
B
